version: '3.7'
services:
  postgres-db:
    image: postgres:13.0
    environment:
      POSTGRES_PASSWORD: sucasa
      POSTGRES_USER: postgres
      POSTGRES_DB: sucasa-db12
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data
    networks:
      - sucasa_net
  sucasa-api12:
    container_name: sucasa-api12
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres-db
    environment:
      PORT: 3333
      POSTGRES_HOST: postgres-db
    ports:
      - '3333:3333'
    networks:
      - sucasa_net
networks:
  sucasa_net:
    driver: bridge
